name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top-lang card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=buefy&locale=cn&hide_border=true&layout=compact&langs_count=10&custom_title=这货都写过啥
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate wakatime card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: wankkoree&theme=buefy&locale=cn&hide_border=true&layout=compact&langs_count=10&custom_title=这货最近%207%20天写了啥&range=last_7_days
          path: profile/wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=EnableWebViewDebugging
          path: profile/WankkoRee/EnableWebViewDebugging.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=Portrait2Landscape
          path: profile/WankkoRee/Portrait2Landscape.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=BitwiseExpressionSimplifier
          path: profile/WankkoRee/BitwiseExpressionSimplifier.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=SchoolPowerCrawlerAndDisplayor
          path: profile/WankkoRee/SchoolPowerCrawlerAndDisplayor.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=WatchDoger
          path: profile/WankkoRee/WatchDoger.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=rich-LogConsole
          path: profile/WankkoRee/rich-LogConsole.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=protools
          path: profile/WankkoRee/protools.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=BilibiliSuitRushBuy
          path: profile/WankkoRee/BilibiliSuitRushBuy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=ISCCAnalysis
          path: profile/WankkoRee/ISCCAnalysis.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=BurpLoaderKeygenCnF
          path: profile/WankkoRee/BurpLoaderKeygenCnF.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=WankkoRee&repo=CTFd-with-Whale-and-H1ve
          path: profile/WankkoRee/CTFd-with-Whale-and-H1ve.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 推送
        id: push
        uses: nicholasgriffintn/github-branch-deployment-action@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: profile
          FOLDER: profile
          MESSAGE: "Update README cards"
